twig:
    form_themes: ['bootstrap_5_layout.html.twig']
    default_path: '%kernel.project_dir%/templates'
    globals:
        tinymce_config:
            promotion: false

when@test:
    twig:
        strict_variables: true
